apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ecom-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: product-details-ds
spec:
  host: product-service
  subsets:
  - name: version-v1
    labels:
      version: v1
  - name: version-v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ecom-ui-ds
spec:
  host: ecom-ui-service
  subsets:
  - name: version-v1
    labels:
      version: v1
  - name: version-v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ecom-vs
spec:
  hosts:
  - "*"
  gateways:
  - ecom-gateway
  http:
  - match:
    - uri:
        prefix: /details
    route:
    - destination:
           host: product-service
           subset: version-v1       # this should be the name mentioned in the destination rule
           port:
              number: 9001
      weight: 75
    - destination:
           host: product-service
           subset: version-v2       # this should be the name mentioned in the destination rule
           port:
              number: 9001
      weight: 25
  - match:
    - uri: #example showing traffic management using header. Same /home endpoint will end up in 2 different api end points depends on the header
        prefix: /home
      headers:
        MyHeader:
            exact: MyValue
    route:
    - destination:
        host: ecom-ui-service #this should be the service name
        subset: version-v2       # this should be the name mentioned in the destination rule
        port:
          number: 9000
  - match:
    - uri: #example showing traffic management using header
        prefix: /home
    route:
    - destination:
        host: ecom-ui-service #this should be the service name
        subset: version-v1       # this should be the name mentioned in the destination rule
        port:
          number: 9000
          